### ISSUE TITLE
in readme config/app.php  providers section nameSpace error

### ISSUE THREAD

**Issue by SAJDEV-s** [misterspelik/laravel-pdf#3]
```php   
	'providers' => [
	// ...
	misterspelik\LaravelPdf\Providers\PdfServiceProvider::class
       ]
	to
       'providers' => [
	// ...
	misterspelik\LaravelPdf\PdfServiceProvider::class
       ]
```

**Comment by misterspelik** [comment]
Hello @SAJDEV-s hope you are doing well.
This is the description fir the 2nd version of the package (the current one) meanwhile you installed the 1st one.
This is the reason why you have the discrepancy between the namespaces (which is the BC-break).

Please use the 2nd version which is more functional as well
